binarizer:
  g2p:
    preprocessors:
      - id: filter-punctuation
      - id: strip-whitespace
      - id: lowercase
    tokenizers:
      - id: whitespace
      - id: cjk
    converters:
      # Chinese: hanzi
      - id: chinese-pinyin
        kwargs:
          dict_path: "dictionaries/ds-zh-pinyin-lite.txt"
      # Chinese: pinyin
      - id: dictionary
        language: zh
        kwargs:
          dict_path: "dictionaries/ds-zh-pinyin-lite.txt"
      # Japanese: kanji + kana (use languages=["ja"] or ["jpn"] for Japanese text)
      - id: japanese-mecab
        kwargs:
          dict_path: "dictionaries/japanese_dict_full.txt"
          nbest: 32
          double_written_sokuon: false
      # Japanese: romaji
      - id: dictionary
        language: ja,jpn
        kwargs:
          dict_path: "dictionaries/japanese_dict_full.txt"
      # English: dictionary + lstm
      - id: lstm
        language: en
        kwargs:
          dict_path: "dictionaries/ds_cmudict-07b.txt"
          model_path: "assets/LstmG2p-Eng"
      # English: pure dictionary
  #      - id: dictionary
  #        language: en
  #        kwargs:
  #          dict_path: "dictionaries/ds_cmudict-07b.txt"
  vocabulary:
    prebuilt_vocab_file: null
    global_symbols: [AP, SP, EP, GS, sil, br, pau]
    stop_symbols: [AP, SP, EP, GS, sil, br, pau]
    merged_groups:
      - [ja/um, zh/um]
